# Generated by Django 6.0.6 on 2026-07-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('rsvp_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_guests', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Entrée, Dessert, Dietary Preference', max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='rsvp.event')),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rsvp.menucategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('attending', models.CharField(choices=[('yes', 'Yes, I will attend'), ('no', 'No, I cannot attend'), ('maybe', 'Maybe')], default='yes', max_length=5)),
                ('dietary_notes', models.TextField(blank=True, help_text='Allergies or other dietary requirements')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='rsvp.event')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dietary_notes', models.TextField(blank=True)),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='rsvp.rsvp')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMemberMenuSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_selections', to='rsvp.familymember')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.menuitem')),
            ],
            options={
                'unique_together': {('family_member', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='RSVPMenuSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.menuitem')),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_selections', to='rsvp.rsvp')),
            ],
            options={
                'unique_together': {('rsvp', 'menu_item')},
            },
        ),
    ]
