# Generated by Django 6.0.6 on 2026-07-02 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rsvp.event')),
                ('rsvp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='rsvp.rsvp')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='InvitedFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='rsvp.invitation')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
